# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\getinfo.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetinfo(HttpRunner):

    config = (
        Config("/getinfo")
        .variables(**{"token": "20099490_12_ac848172516276de_1_43526555"})
        .base_url("http://172.16.1.202:5000")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("/info")
            .get("/info")
            .with_params(**{"token": "$token"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Host": "172.16.1.202:5000",
                    "Postman-Token": "39e1fd5d-d505-4943-825a-5314a541bad1",
                    "User-Agent": "PostmanRuntime/7.26.5",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.data.age", 18)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetinfo().test_start()
