# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\login2.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin2(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "casename-username-password-expect": [
                    ["用户名密码正确", "zhaoxiongkuan", "12345678", "success"],
                    ["密码错误", "zhaoxiongkuan", "123456789", "用户名/密码错误"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("$casename").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .post("http://172.16.1.202:5000/login")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Content-Length": "291",
                    "Host": "172.16.1.202:5000",
                    "Postman-Token": "e584dba3-9651-4166-94b7-4487e4a3b0eb",
                    "User-Agent": "PostmanRuntime/7.26.5",
                }
            )
            .with_data({"username": "$username", "password": "$password"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "$expect")
            .assert_equal("body.status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin2().test_start()
