# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .post("http://172.16.1.202:5000/login")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Content-Length": "291",
                    "Host": "172.16.1.202:5000",
                    "Postman-Token": "88492415-74ee-4fc5-bd1a-68ec50415d8f",
                    "User-Agent": "PostmanRuntime/7.26.8",
                }
            )
            .with_data({"password": "12345678", "username": "zhaoxiongkuan"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status_code", 200)
            .assert_equal("body.token", "20099490_12_ac848172516276de_1_43526555")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
